### PR TITLE
getReductions (latest)

### PR DESCRIPTION
**Pull request by avido**
- get latest reductions filename
- get latest reductions.

**note**
Of course method isn't available in test...

### CODE REVIEW

**Comment by mwienk** [comment]
Hi @avido, thanks for your contribution, any idea why the build fails?

**Comment by avido** [comment]
@mwienk actually not really... My best guess would be the unit tests however i'm not completely sure why Travis is marking the build failed.

**Comment by avido** [comment]
@mwienk Does travis automatically build if the pull request is updated?

**Comment by mwienk** [comment]
Yeah it builds automatically, and the tests seem to fail indeed. Do they work locally?

**Comment by avido** [comment]
@mwienk seems the config has changed... If i view the job config for the latest pull (and the failing one before) the global_env params are missing.

**Comment by mwienk** [comment]
I think the problem is that a PR cannot use the Travis secrets (api keys). I have edited and merged your changes (created a new ReductionList entity). Thanks again for your contribution!

In the future, could you create your PRs agains the develop branch? That way I don't have to create a release after every PR (I would like to have a stable master branch and a bleeding edge develop branch).

**Comment by avido** [comment]
@mwienk Thanks will do. !
About your change(s) the type declaration "string" in the ReductionList entity (methods setData & setFilename) requires a php min version 7.0.0 (http://php.net/manual/en/functions.arguments.php#functions.arguments.type-declaration) 
However the composer project setup requires a php min version 5.5.9 
Maybe wise to remove the type declaration...

**Comment by mwienk** [comment]
Good catch, I have removed it. Though it is weird that the build did succeed, as it also builds it against 5.x infrastructure.

**Pull request merged**
